language: objective-c
xcode_project: JRAuditableEntity.xcodeproj
xcode_scheme: JRAuditableEntity
xcode_sdk: iphonesimulator9.3
before_install: gem install cocoapods slather -N
after_success: 
    - pod lib lint --quick
    - slather  
notifications:
  slack:
    secure: FnRNBxMVFTUsg4k62wEoSeZEgSApNrXMCDC4nh+t0jp+vb7XHA6g9vBunUzCRHIr0Yp5E57KHu/K6+TWxctvhGW5gMrrpxOPZcxpgmybOTPmUnswB9uch3hDmL6/tAJJHSFX67tV1F+Z4XTEb7UTJUQpa8d+yeK/uGJhVaF88RhsVBATJjMYlGh74VxFL3a20eeVEnDDAfyQf+kx7Ef/QWrqk6eRL+Dmifc1SBaGNSD02Mp8QjyuqS4cbAM77ys+hTVZiDdprcTrclmKhIHnnuclQfNFtokKhYs8iFN2Gj1BwXSJXNDzDiL/T/cDsHiFpRoMvUbbwS69nAZLfsUid54uXWBjCct2lVhzJn/IcFekVRfTKsPTK1kD5EBeM8gOx4YEmlcRrxYHCU31bvmp01tff2XtjEISiBz+qgkD3BJ2yOU23pjRs59bMLR2jVo+JVQ6MiKXYc/o0fhG/ochYkaVspx6hH6dZWQ+Vjyv9Enen1tCNC9fIL7V7gD0jsLrYRJYFqxoM7tlPoxkoXHwtYightTcDhVkAWfBQ+rK5Fxu9HlQDJ+qyPGvGhhT1FSA/eeBadszrRGdsSvVQ3qETInElD6ZIZrlMEenjSCiizD6no6OEnk8O4e4I1789/GdK65nFQeCt8CwEyfG3Ymv86RLtHmmnS/zGWNKgRAYhME=
